url: "https://lucio.github.io/"
baseurl: ""
title: OHA Website
description: OHA website done by Team Lucio on HACC 2017
google_analytics: 
show_downloads: true
theme: jekyll-theme-leap-day
gems:
  - jekyll-mentions
